 vim.keymap.set('n', '<leader>sr', '<CMD>Telescope oldfiles<CR>', { desc = '[R]ecent' })
 vim.keymap.set('n', '<leader>sb', '<CMD>Telescope buffers<CR>', { desc = '[B]uffers' })
 vim.keymap.set('n', '<leader>sg', '<CMD>Telescope live_grep<CR>', { desc = '[G]rep' })
 vim.keymap.set('n', '<leader>st', '<CMD>Telescope<CR>', { desc = 'Telescope' })
 vim.keymap.set('n', '<leader>gf', '<CMD>Telescope git_files<CR>', { desc = 'search [F]iles' })
 vim.keymap.set('n', '<leader><space>', '<CMD>Telescope find_files<CR>', { desc = 'find [F]iles' })
